import type { AnnualOverviewData, PulseDetailData, PulseIndexItem, SensorDetailData, SensorIndexItem } from "@/lib/types/ui-data";
import type { ExplorerState } from "./explorer-state";
import ExplorerStatus from "./ExplorerStatus";

const dt=(v:string)=>new Intl.DateTimeFormat("en-AU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
const label=(v:string)=>v.replaceAll("_"," ");
type Props={annual:AnnualOverviewData;filtered:PulseIndexItem[];filters:ExplorerState;pulse:PulseIndexItem|null;sensor:SensorIndexItem|null;pulseDetail:PulseDetailData|null;sensorDetail:SensorDetailData|null;pulseStatus:string;sensorStatus:string;pulseError:string|null;sensorError:string|null;onCloseSensor:()=>void;onRetryPulse:()=>void;onRetrySensor:()=>void};

export default function ContextInspector(p:Props){
  if(p.sensor)return <SensorInspector {...p} sensor={p.sensor}/>;
  if(p.pulse)return <PulseInspector {...p} pulse={p.pulse}/>;
  const above=p.filtered.filter(x=>x.direction==="above").length;
  const counts={localized:p.filtered.filter(x=>x.scope==="localized").length,broad:p.filtered.filter(x=>x.scope==="broad").length,network:p.filtered.filter(x=>x.scope==="network_wide").length};
  const pending=p.filtered.filter(x=>x.evidenceReadiness==="auto_matched_pending_review").length;
  const active=[p.filters.month&&`month ${p.filters.month}`,p.filters.direction&&`${p.filters.direction} expected`,...p.filters.scopes.map(label),...p.filters.evidenceReadiness.map(label)].filter(Boolean);
  return <aside className="inspector" aria-labelledby="inspector-title"><InspectorHead kicker="Annual overview" title="2025 research window"/><dl className="facts"><Fact k="Study period" v={`${p.annual.studyPeriod.start.slice(0,10)} — ${p.annual.studyPeriod.end.slice(0,10)}`}/><Fact k="Representative sensors" v={p.annual.summary.sensorCount}/><Fact k="All Pulses" v={p.annual.summary.pulseCount}/><Fact k="Filtered Pulses" v={p.filtered.length}/><Fact k="Above / below" v={`${above} / ${p.filtered.length-above}`}/><Fact k="Localized / broad / network" v={`${counts.localized} / ${counts.broad} / ${counts.network}`}/><Fact k="Missing observations" v={p.annual.summary.missingRows}/><Fact k="Matches pending review" v={pending}/></dl><Section title="Current filters"><p>{active.length?active.join(" · "):"All annual Pulses are visible."}</p><p>{p.filtered.length} of {p.annual.summary.pulseCount} Pulses are visible.</p></Section><p className="boundary">Pulse counts describe departures from expected rhythm, not total pedestrian volume.</p></aside>;
}

function SensorInspector(p:Props&{sensor:SensorIndexItem}){const d=p.sensorDetail,member=p.pulse?.memberSensorIds.includes(p.sensor.sensorId);return <aside className="inspector" aria-labelledby="inspector-title"><div className="inspector-title-row"><InspectorHead kicker="Sensor focus" title={p.sensor.locationName}/><button className="close-context" onClick={p.onCloseSensor}>Close Sensor</button></div><dl className="facts"><Fact k="Sensor ID" v={p.sensor.sensorId}/><Fact k="Coordinates" v={`${p.sensor.coordinates.latitude.toFixed(5)}, ${p.sensor.coordinates.longitude.toFixed(5)}`}/><Fact k="Coverage" v={`${(p.sensor.coverageRate*100).toFixed(2)}%`}/><Fact k="Available / missing" v={`${p.sensor.availableHours.toLocaleString()} / ${p.sensor.missingHours}`}/><Fact k="Location type" v={p.sensor.locationType}/></dl>{p.pulse&&<p className={`membership ${member?"yes":"no"}`}>{member?"This sensor is a member of the selected Pulse.":"This sensor is not a member of the selected Pulse."}</p>}<DetailState status={p.sensorStatus} error={p.sensorError} retry={p.onRetrySensor}>{d&&<><Section title="Research metadata"><p>Installed {d.installationDate??"date unavailable"}.</p><p>{d.selection.inclusionReason}</p></Section><Section title="Regular rhythm"><p><b>{d.regularRhythm.length}</b> weekday × hour cells available.</p><p>Sample size {Math.min(...d.regularRhythm.map(x=>x.sampleSize))}–{Math.max(...d.regularRhythm.map(x=>x.sampleSize))}; confidence: {[...new Set(d.regularRhythm.map(x=>x.baselineConfidence))].join(", ")}.</p><span className="future">Full rhythm visualisation follows in a later slice.</span></Section><Section title="Pulse participation"><p><b>{d.pulseParticipation.length}</b> Pulses across the complete year.</p></Section>{d.limitations.map(x=><p className="boundary" key={x}>{x}</p>)}<p className="media-empty">No confirmed media mapping yet.</p></>}</DetailState></aside>}

function PulseInspector(p:Props&{pulse:PulseIndexItem}){const d=p.pulseDetail;return <aside className="inspector" aria-labelledby="inspector-title"><InspectorHead kicker="Pulse selected" title={dt(p.pulse.start)}/><dl className="facts"><Fact k="Direction" v={`${p.pulse.direction} expected`}/><Fact k="Scope" v={label(p.pulse.scope)}/><Fact k="Duration" v={`${p.pulse.durationHours} hours`}/><Fact k="Max active sensors" v={p.pulse.maxActiveSensorCount}/><Fact k="Member sensors" v={p.pulse.memberSensorCount}/><Fact k="Episodes" v={p.pulse.episodeCount}/><Fact k="Strength band" v={label(p.pulse.strengthBand)}/><Fact k="Evidence state" v={label(p.pulse.evidenceReadiness)}/></dl><DetailState status={p.pulseStatus} error={p.pulseError} retry={p.onRetryPulse}>{d&&<><Section title="Context"><ContextRow name="Public holiday" value={context(d.context.publicHoliday)}/><ContextRow name="School holiday" value={context(d.context.schoolHoliday)}/><ContextRow name="Daylight saving" value={context(d.context.daylightSaving)}/><ContextRow name="Weather" value={d.context.weather.overlaps?`${d.context.weather.rainyHourCount} rainy hours; max wind ${d.context.weather.windSpeedMax??"—"}`:"No provisional weather disruption overlap"}/><ContextRow name="Planned works" value="Deferred — not assessed"/></Section><Section title={`Evidence matches · ${d.evidence.matchCount}`}>{d.evidence.items.length===0?<p>No evidence items are linked within the current review scope.</p>:d.evidence.items.map(e=><article className="evidence-item" key={e.matchId}><h4>{e.name}</h4><p>{e.source.name}</p><ul><li>{e.temporalOverlap.hours} hour temporal overlap</li><li>{label(e.spatialRelevance)}</li><li>{label(e.directionConsistency)}</li><li>Automatic match confidence: {e.automaticMatchConfidence}</li><li>Pending review</li></ul>{e.source.url&&<a href={e.source.url} target="_blank" rel="noreferrer">Open source ↗</a>}</article>)}</Section><p className="boundary">Evidence overlap does not establish causation.</p><Section title="Quality & provenance"><p>Baseline confidence: {d.quality.baselineConfidence}. Weather-missing hours: {d.quality.weatherMissingHourCount}.</p><p className="mono">{d.provenance.processingVersions.explanationReady}</p></Section></>}</DetailState></aside>}

function InspectorHead({kicker,title}:{kicker:string;title:string}){return <header className="inspector-head"><span className="eyebrow">{kicker}</span><h2 id="inspector-title">{title}</h2></header>}
function Fact({k,v}:{k:string;v:React.ReactNode}){return <div><dt>{k}</dt><dd>{v}</dd></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="inspector-section"><h3>{title}</h3>{children}</section>}
function ContextRow({name,value}:{name:string;value:string}){return <p className="context-row"><b>{name}</b><span>{value}</span></p>}
function context(v:{availability:string;overlaps:boolean|null;labels:string[]}){return v.availability==="deferred"?"Deferred":v.overlaps?(v.labels.join(", ")||"Overlap recorded"):"No overlap recorded"}
function DetailState({status,error,retry,children}:{status:string;error:string|null;retry:()=>void;children:React.ReactNode}){if(status==="loading")return <ExplorerStatus>Loading detail…</ExplorerStatus>;if(status==="error")return <ExplorerStatus kind="error" onRetry={retry}>{error??"Detail payload could not be loaded."}</ExplorerStatus>;return <>{children}</>}
