export type ISODate=string; export type ISODateTime=string; export type SensorId=string; export type PulseId=string; export type EpisodeId=string; export type EvidenceId=string;
export type Direction="above"|"below"; export type SeriesDirection=Direction|"near"|"not_applicable"; export type PulseScope="localized"|"broad"|"network_wide";
export type BaselineConfidence="high"|"medium"|"low"|"insufficient"; export type StrengthBand="strong"|"extreme"|"mixed_strong_extreme";
export type EvidenceReadiness="auto_matched_pending_review"|"not_in_manual_review_scope"|"partially_reviewed"|"reviewed_verified_overlap"|"reviewed_plausible_association"|"reviewed_insufficient_evidence"|"reviewed_unexplained"|"reviewed_data_quality_issue"|"mixed_review_status";
export type EvidenceReviewDecision="pending_review"|"verified_overlap"|"plausible_association"|"insufficient_evidence"|"unexplained"|"data_quality_issue"|"rejected";
export type SourceCompleteness="complete"|"project_derived_without_url"|"not_researched"; export type ContextAvailability="available"|"deferred"; export type WeekdayIndex=0|1|2|3|4|5|6;
export interface ProcessingVersions {contextPanel:string;baselines:string;scoring:string;interpretation:string;episodes:string;pulses:string;contextEnrichment:string;evidenceMatching:string;explanationReady:string}
export interface UiManifest {schemaVersion:string;dataVersion:string;sensorMode:"REPRESENTATIVE_12";inputDigests:{logicalName:string;sha256:string}[];processingVersions:ProcessingVersions;recordCounts:Record<string,number>;outputFileCounts:Record<string,number>;outputDigests:{payloadTreeSha256:string;pulseDetailTreeSha256:string;sensorDetailTreeSha256:string};displayWindowPolicy:{paddingHours:number;clampToStudyPeriod:true};payloadStatistics:Record<string,number|string>}
export interface MonthlyPulseSummary {month:number;total:number;above:number;below:number;localized:number;broad:number;networkWide:number;autoMatchedPendingReview:number;outsideManualReviewScope:number}
export interface AnnualOverviewData {schemaVersion:string;dataVersion:string;sensorMode:"REPRESENTATIVE_12";studyPeriod:{start:ISODateTime;end:ISODateTime;timezone:string};summary:{sensorCount:number;nominalHourlyKeys:number;sensorHourRows:number;observedRows:number;missingRows:number;baselineGroupCount:number;episodeCount:number;pulseCount:number;pulseDirectionCounts:Record<Direction,number>;pulseScopeCounts:Record<PulseScope,number>;evidenceFactCount:number;evidenceMatchCount:number;reviewedMatchCount:number};monthly:MonthlyPulseSummary[];processingVersions:ProcessingVersions;limitations:string[]}
export interface Coordinates {latitude:number;longitude:number}
export interface SensorIndexItem {sensorId:SensorId;locationName:string;shortLabel:string;sensorName:string;coordinates:Coordinates;coverageRate:number;availableHours:number;missingHours:number;locationType:string;selectionTier:string}
export interface RegularRhythmCell {weekdayIndex:WeekdayIndex;hour:number;median:number;p25:number;p75:number;p05:number;p95:number;sampleSize:number;baselineConfidence:BaselineConfidence}
export interface SensorDetailData {schemaVersion:string;dataVersion:string;sensorId:SensorId;sensorName:string;locationName:string;shortLabel:string;precinct:string|null;status:string;locationType:string;installationDate:ISODate|null;coordinates:Coordinates;coverage:{rate:number;availableHours:number;missingHours:number};selection:{tier:string;inclusionReason:string};regularRhythm:RegularRhythmCell[];pulseParticipation:{pulseId:PulseId;episodeIds:EpisodeId[]}[];mediaIds:string[];limitations:string[]}
export interface PulseIndexItem {pulseId:PulseId;start:ISODateTime;end:ISODateTime;month:number;direction:Direction;scope:PulseScope;durationHours:number;maxActiveSensorCount:number;memberSensorCount:number;memberSensorIds:SensorId[];episodeCount:number;strengthBand:StrengthBand;evidenceMatchCount:number;evidenceReadiness:EvidenceReadiness;requiresHumanReview:boolean;storyCategory:string|null}
export interface EpisodeSummary {episodeId:EpisodeId;sensorId:SensorId;sensorLabel:string;start:ISODateTime;end:ISODateTime;durationHours:number;direction:Direction;peakAbsScore:number;meanAbsScore:number;strengthBand:StrengthBand;baselineConfidence:BaselineConfidence;interpretationWarnings:string[]}
export interface SeriesPoint {timestamp:ISODateTime;sensorId:SensorId;observedCount:number|null;isMissing:boolean;missingReason:string|null;expected:{median:number|null;p25:number|null;p75:number|null;p05:number|null;p95:number|null;sampleSize:number|null;baselineConfidence:BaselineConfidence|null};robustZScore:number|null;anomalyStrength:number|null;scoringConfidence:number|null;direction:SeriesDirection;isPulseMemberAtTimestamp:boolean}
export interface SpatialFramePoint {sensorId:SensorId;observedCount:number|null;isMissing:boolean;direction:SeriesDirection;anomalyStrength:number|null;isPulseMemberAtTimestamp:boolean}
export interface SpatialFrame {timestamp:ISODateTime;activeSensorCount:number;availableSensorCount:number;points:SpatialFramePoint[]}
export interface ContextSummary {publicHoliday:{availability:ContextAvailability;overlaps:boolean|null;labels:string[]};schoolHoliday:{availability:ContextAvailability;overlaps:boolean|null;labels:string[]};daylightSaving:{availability:ContextAvailability;overlaps:boolean|null;labels:string[]};weather:{availability:ContextAvailability;overlaps:boolean|null;rainyHourCount:number;rainTotal:number|null;temperatureMean:number|null;windSpeedMax:number|null};plannedWorks:{availability:ContextAvailability;overlaps:boolean|null}}
export interface EvidenceDetailData {evidenceId:EvidenceId;matchId:string;name:string;type:string;source:{name:string;category:string;url:string|null;accessedDate:ISODate|null;completeness:SourceCompleteness};interval:{start:ISODateTime;end:ISODateTime};location:{name:string|null;precinct:string|null;coordinates:Coordinates|null;spatialScope:string};expectedDirection:Direction|"unknown";evidenceConfidence:"high"|"moderate"|"low";temporalOverlap:{overlaps:boolean;hours:number;candidateRatio:number;evidenceRatio:number};spatialRelevance:string;directionConsistency:"consistent"|"inconsistent"|"indeterminate";automaticMatchConfidence:"high"|"moderate"|"low";reviewStatus:EvidenceReviewDecision;reviewedAt:ISODateTime|null;notes:string|null;warnings:string[];causalClaimAllowed:false}
export interface PulseDetailData {schemaVersion:string;dataVersion:string;pulse:PulseIndexItem&{activeHourCount:number;strength:{maxPeakAbsScore:number;meanPeakAbsScore:number;maxMeanAbsScore:number}};displayWindow:{requestedStart:ISODateTime;requestedEnd:ISODateTime;actualStart:ISODateTime;actualEnd:ISODateTime;paddingHours:number;wasClamped:boolean};episodes:EpisodeSummary[];series:SeriesPoint[];spatialFrames:SpatialFrame[];context:ContextSummary;evidence:{readiness:EvidenceReadiness;matchCount:number;reviewedMatchCount:number;items:EvidenceDetailData[];causalClaimAllowed:false};quality:{weatherMissingHourCount:number;baselineConfidence:BaselineConfidence;sourceCompleteness:SourceCompleteness};provenance:{processingVersions:ProcessingVersions;baselineMethod:string;primaryScoreSource:string}}
